# Check formatting of toml/md files using dprint.
# Rust format checking is done in the CI workflow.

name: fmt

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dprint
        uses: actions/cache@v4
        with:
          path: |
            ~/.dprint
            ~/.cache/dprint
          key: dprint

      - name: Install dprint
        run: |
          if [ ! -f $HOME/.dprint/bin/dprint ]; then
            curl -fsSL https://dprint.dev/install.sh | sh
          fi
          echo $HOME/.dprint/bin >> $GITHUB_PATH

      - run: dprint check
